version: '3'
services:
  transmission:
    image: dperson/transmission
    restart: always
    volumes:
      - ./data/:/var/lib/transmission-daemon
    environment:
      - TRUSER=admin
      - TRPASSWD=<yourpassphrasehere>
      - USERID=1000
      - GROUPID=1000
      - VIRTUAL_PORT=9091
      - VIRTUAL_HOST=<sub.yourdomain.here>
      - LETSENCRYPT_HOST=<sub.yourdomain.here>
      - LETSENCRYPT_EMAIL=<email.yourdomain.here>
    ports:
      - 51413:51413
      - 51413:51413/udp
networks:
  default:
    external:
      name: nginx-proxy
